<?php

use Illuminate\Database\Seeder;

class PermissionSeed extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $items = [
            
            ['id' => 1, 'title' => 'user_management_access',],
            ['id' => 2, 'title' => 'permission_access',],
            ['id' => 3, 'title' => 'permission_create',],
            ['id' => 4, 'title' => 'permission_edit',],
            ['id' => 5, 'title' => 'permission_view',],
            ['id' => 6, 'title' => 'permission_delete',],
            ['id' => 7, 'title' => 'role_access',],
            ['id' => 8, 'title' => 'role_create',],
            ['id' => 9, 'title' => 'role_edit',],
            ['id' => 10, 'title' => 'role_view',],
            ['id' => 11, 'title' => 'role_delete',],
            ['id' => 12, 'title' => 'user_access',],
            ['id' => 13, 'title' => 'user_create',],
            ['id' => 14, 'title' => 'user_edit',],
            ['id' => 15, 'title' => 'user_view',],
            ['id' => 16, 'title' => 'user_delete',],
            ['id' => 17, 'title' => 'admin_setting_access',],
            ['id' => 18, 'title' => 'admin_setting_create',],
            ['id' => 19, 'title' => 'admin_setting_edit',],
            ['id' => 20, 'title' => 'admin_setting_view',],
            ['id' => 21, 'title' => 'admin_setting_delete',],
            ['id' => 22, 'title' => 'category_access',],
            ['id' => 23, 'title' => 'category_create',],
            ['id' => 24, 'title' => 'category_edit',],
            ['id' => 25, 'title' => 'category_view',],
            ['id' => 26, 'title' => 'category_delete',],
            ['id' => 27, 'title' => 'collection_access',],
            ['id' => 28, 'title' => 'collection_create',],
            ['id' => 29, 'title' => 'collection_edit',],
            ['id' => 30, 'title' => 'collection_view',],
            ['id' => 31, 'title' => 'collection_delete',],
            ['id' => 32, 'title' => 'collections_image_access',],
            ['id' => 33, 'title' => 'collections_image_create',],
            ['id' => 34, 'title' => 'collections_image_edit',],
            ['id' => 35, 'title' => 'collections_image_view',],
            ['id' => 36, 'title' => 'collections_image_delete',],
            ['id' => 37, 'title' => 'comment_access',],
            ['id' => 38, 'title' => 'comment_create',],
            ['id' => 39, 'title' => 'comment_edit',],
            ['id' => 40, 'title' => 'comment_view',],
            ['id' => 41, 'title' => 'comment_delete',],
            ['id' => 42, 'title' => 'comments_like_access',],
            ['id' => 43, 'title' => 'comments_like_create',],
            ['id' => 44, 'title' => 'comments_like_edit',],
            ['id' => 45, 'title' => 'comments_like_view',],
            ['id' => 46, 'title' => 'comments_like_delete',],
            ['id' => 47, 'title' => 'country_access',],
            ['id' => 48, 'title' => 'country_create',],
            ['id' => 49, 'title' => 'country_edit',],
            ['id' => 50, 'title' => 'country_view',],
            ['id' => 51, 'title' => 'country_delete',],
            ['id' => 52, 'title' => 'download_access',],
            ['id' => 53, 'title' => 'download_create',],
            ['id' => 54, 'title' => 'download_edit',],
            ['id' => 55, 'title' => 'download_view',],
            ['id' => 56, 'title' => 'download_delete',],
            ['id' => 57, 'title' => 'follower_access',],
            ['id' => 58, 'title' => 'follower_create',],
            ['id' => 59, 'title' => 'follower_edit',],
            ['id' => 60, 'title' => 'follower_view',],
            ['id' => 61, 'title' => 'follower_delete',],
            ['id' => 62, 'title' => 'image_access',],
            ['id' => 63, 'title' => 'image_create',],
            ['id' => 64, 'title' => 'image_edit',],
            ['id' => 65, 'title' => 'image_view',],
            ['id' => 66, 'title' => 'image_delete',],
            ['id' => 67, 'title' => 'images_reported_access',],
            ['id' => 68, 'title' => 'images_reported_create',],
            ['id' => 69, 'title' => 'images_reported_edit',],
            ['id' => 70, 'title' => 'images_reported_view',],
            ['id' => 71, 'title' => 'images_reported_delete',],
            ['id' => 72, 'title' => 'language_access',],
            ['id' => 73, 'title' => 'language_create',],
            ['id' => 74, 'title' => 'language_edit',],
            ['id' => 75, 'title' => 'language_view',],
            ['id' => 76, 'title' => 'language_delete',],
            ['id' => 77, 'title' => 'like_access',],
            ['id' => 78, 'title' => 'like_create',],
            ['id' => 79, 'title' => 'like_edit',],
            ['id' => 80, 'title' => 'like_view',],
            ['id' => 81, 'title' => 'like_delete',],
            ['id' => 82, 'title' => 'notification_access',],
            ['id' => 83, 'title' => 'notification_create',],
            ['id' => 84, 'title' => 'notification_edit',],
            ['id' => 85, 'title' => 'notification_view',],
            ['id' => 86, 'title' => 'notification_delete',],
            ['id' => 87, 'title' => 'page_access',],
            ['id' => 88, 'title' => 'page_create',],
            ['id' => 89, 'title' => 'page_edit',],
            ['id' => 90, 'title' => 'page_view',],
            ['id' => 91, 'title' => 'page_delete',],
            ['id' => 92, 'title' => 'reply_access',],
            ['id' => 93, 'title' => 'reply_create',],
            ['id' => 94, 'title' => 'reply_edit',],
            ['id' => 95, 'title' => 'reply_view',],
            ['id' => 96, 'title' => 'reply_delete',],
            ['id' => 97, 'title' => 'reserved_access',],
            ['id' => 98, 'title' => 'reserved_create',],
            ['id' => 99, 'title' => 'reserved_edit',],
            ['id' => 100, 'title' => 'reserved_view',],
            ['id' => 101, 'title' => 'reserved_delete',],
            ['id' => 102, 'title' => 'stock_access',],
            ['id' => 103, 'title' => 'stock_create',],
            ['id' => 104, 'title' => 'stock_edit',],
            ['id' => 105, 'title' => 'stock_view',],
            ['id' => 106, 'title' => 'stock_delete',],
            ['id' => 107, 'title' => 'users_reported_access',],
            ['id' => 108, 'title' => 'users_reported_create',],
            ['id' => 109, 'title' => 'users_reported_edit',],
            ['id' => 110, 'title' => 'users_reported_view',],
            ['id' => 111, 'title' => 'users_reported_delete',],
            ['id' => 112, 'title' => 'visit_access',],
            ['id' => 113, 'title' => 'visit_create',],
            ['id' => 114, 'title' => 'visit_edit',],
            ['id' => 115, 'title' => 'visit_view',],
            ['id' => 116, 'title' => 'visit_delete',],
            ['id' => 117, 'title' => 'plan_access',],
            ['id' => 118, 'title' => 'plan_create',],
            ['id' => 119, 'title' => 'plan_edit',],
            ['id' => 120, 'title' => 'plan_view',],
            ['id' => 121, 'title' => 'plan_delete',],
            ['id' => 122, 'title' => 'user_plan_access',],
            ['id' => 123, 'title' => 'user_plan_create',],
            ['id' => 124, 'title' => 'user_plan_edit',],
            ['id' => 125, 'title' => 'user_plan_view',],
            ['id' => 126, 'title' => 'user_plan_delete',],
            ['id' => 127, 'title' => 'payment_method_access',],
            ['id' => 128, 'title' => 'payment_method_create',],
            ['id' => 129, 'title' => 'payment_method_edit',],
            ['id' => 130, 'title' => 'payment_method_view',],
            ['id' => 131, 'title' => 'payment_method_delete',],
            ['id' => 132, 'title' => 'user_payment_access',],
            ['id' => 133, 'title' => 'user_payment_create',],
            ['id' => 134, 'title' => 'user_payment_edit',],
            ['id' => 135, 'title' => 'user_payment_view',],
            ['id' => 136, 'title' => 'user_payment_delete',],

        ];

        foreach ($items as $item) {
            \App\Permission::create($item);
        }
    }
}
